### ISSUE TITLE
PokemonSwSh: Autonomous Egg Hatching

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/ComputerControl#1]
Moved from: https://github.com/PokemonAutomation/SwSh-Arduino/issues/7

Add an autonomous egg program that requires minimal user intervention:

    Start with one box of eggs.
    Program looks for a complete column to hatch.
    If there are no complete columns, run egg fetching loop until there are.
    If the box is full, run egg hatching loop until it isn't.
    Otherwise, run egg-combined loop.
    Release non-shinies on the fly.
    Deposit shinies in the box before the eggs.
    Egg hatching goes until entire party is hatched. (tolerance to late hatching eggs)
    If an egg hatches unexpectedly early, fly back to daycare and travel to spin location. (tolerance to early hatching eggs)
    Shinies can be detected both by animation and by the shiny-symbol when you're about to release.
    Keep track of stats. See if shiny detection is reliable to determine shiny type from hatch animation.
    Program can run uninterrupted until the box for shinies fills up.

**Comment by pifopi** [comment]
done ?
