### ISSUE TITLE
[REQ] - SV Auction House Resets - there's no option for SV in the form btw

### ISSUE THREAD

**Issue by Kensairabbit37** [PokemonAutomation/ComputerControl#112]
**Important**
- Add your title after **[REQ] - **
- **Replace** the space inside the **[ ]** with a **x** to mark one of the options
- Replace the text inside "()" with what is required
- _**Bear in mind requests are subject to dev availability and/or interest**_

**Game**
- [X] Sword/Shield
- [ ] Brilliant Diamond/Shining Pearl
- [ ] Legend Arceus
- [ ] Nintendo Switch Features

**Type**
- [X] New Program
- [ ] Improvement to **_(Program Name)_**

**Description**
A program to reset the auction house for specific items would be lovely (e.g. special balls, pp max, gold bottle caps). There's a setup where you save game, close, change the date forward a day, and restart to get new item auctions. If configured properly, the game can then just be soft reset to get new items (without continuous time change). Still tedious which is where the automation would be great. Not sure how the vision works and if it could read the speech bubbles. I imagine if you communicate in the instructions and exact position and camera direction it's doable?

**Additional context**
_(Give more details (if required) on how the program would work, use case, relevance, graphs, images, etc)._

**Comment by pifopi** [comment]
Already done with https://github.com/PokemonAutomation/Arduino-Source/pull/251 It is not available yet in any release though
