### ISSUE TITLE
[REQ] - Academy Ace Tournament farmer

### ISSUE THREAD

**Issue by karasuhebi** [PokemonAutomation/ComputerControl#117]
**Game**
- [ ] Sword/Shield
- [ ] Brilliant Diamond/Shining Pearl
- [ ] Legend Arceus
- [ ] Nintendo Switch Features

**Type**
- [X] New Program
- [ ] Improvement to **_(Program Name)_**

**Description**
_(I think a program like TurboA but that keeps track of what rewards you get when you win the tournament would be nice. Maybe instead of actually keeping track have it just send out a Discord notification with the item name?)_

**Comment by Mysticial** [comment]
Implemented by kichithewolf
