### ISSUE TITLE
PLA - Outbreak Finder - can get stuck on saving screen

### ISSUE THREAD

**Issue by schmidtbauer** [PokemonAutomation/ComputerControl#126]
**Game**
- [ ] Sword/Shield
- [ ] Brilliant Diamond/Shining Pearl
- [X] Legend Arceus
- [ ] Nintendo Switch Features

**Type**
- [ ] New Program
- [X] Improvement to **Outbreak Finder**

**Description**
The PLA programm "Outbreak Finder" can get stuck on the saving screen, while saving the preserve berries.
It looks like it is not waiting long enough for the saving screen to clear (text speed ingame - fast).
This causes multiple saving attempts before stopping, the programm does not recover by itself and needs human intervention.
Sometimes it runs 30+ minutes fine before running into the issue, other times it happens on the first attempt so save the game. 

![image](https://user-images.githubusercontent.com/49582716/225058634-057af638-e168-43a3-a4e5-51a08210c21a.png)

**Steps to replicate issue**
- Start PLA programm
- Leave it running for 30+ minutes

**Comment by Mysticial** [comment]
I know it's been a while, but do you remember if you were running off a cart or digital?

If digital, were you running from SD card? Likewise, is the entire system running emuMMC off a slow SD card?

(trying to give possibilities on why the game would lag like this)

**Comment by Mysticial** [comment]
https://github.com/PokemonAutomation/Arduino-Source/commit/a96dc6fb16c56c0ad46c75291032d4bfd3194bee

**Comment by schmidtbauer** [comment]
I was running the game digital of an SD Card. I tried it with a original Switch and an OLED Switch. Both using this SD Card: SanDisk Extreme microSDXC UHS-I 128 GB A2, C10, V30, U3
