### ISSUE TITLE
[REQ] - Add "finish hatching box" to S/V egg autonomous

### ISSUE THREAD

**Issue by jon-dunn** [PokemonAutomation/ComputerControl#141]
**Important**
- Add your title after **[REQ] - **
- **Replace** the space inside the **[ ]** with a **x** to mark one of the options
- Replace the text inside "()" with what is required
- _**Bear in mind requests are subject to dev availability and/or interest**_

**Game**
- [ ] Sword/Shield
- [ ] Brilliant Diamond/Shining Pearl
- [x] Scarlet/Violet
- [ ] Legend Arceus
- [ ] Nintendo Switch Features

**Type**
- [ ] New Program
- [x ] Improvement to **_(Egg Autonomous)_**

**Description**
_(Add a checkbox to choose whether to finish hatching the box of eggs and/or delete them once the targets have been found)_

**Additional context**
_(As the program generates 30 eggs at a time then hatches them, when the target has been hatched, often you're left with half a box of eggs, which you then have to clear to make way for the next breeding project. Usually I just run egg hatcher then mass release, but it would be nice if there was a toggle to finish the box and clear it automatically)._

**Comment by Mysticial** [comment]
Not sure if we'll do this because the egg program is already super-complicated.

**Comment by Vaedz7** [comment]
I've added a toggle for this but it's untested. If interested test the program using: https://github.com/Vaedz7/Arduino-Source/blob/main/SerialPrograms/Source/PokemonSV/Programs/Eggs/PokemonSV_EggAutonomous.cpp

(I'm testing it now but I can't guarantee it works perfectly.)
