### ISSUE TITLE
[REQ] - S/V size checker

### ISSUE THREAD

**Issue by jon-dunn** [PokemonAutomation/ComputerControl#143]
**Game**
- [ ] Sword/Shield
- [ ] Brilliant Diamond/Shining Pearl
- [ x] Scarlet/Violet
- [ ] Legend Arceus
- [ ] Nintendo Switch Features

**Type**
- [x ] New Program
- [ ] Improvement to **_(Program Name)_**

**Description**
_A program to use the npc in mezagosa to check the sizes of boxes of pokemon at a time to find size marks_

**Additional context**
_Input for number of boxes to check, and whether to stop when a mark candidate is found_

**Comment by Mysticial** [comment]
Nymph already implemented this, but it's still in beta.
