### ISSUE TITLE
[REQ] - Tera Self Farmer Needs Auto Restart

### ISSUE THREAD

**Issue by PhoenixRising26** [PokemonAutomation/ComputerControl#164]
**Important**
- Add your title after **[REQ] - **
- **Replace** the space inside the **[ ]** with a **x** to mark one of the options
- Replace the text inside "()" with what is required
- _**Bear in mind requests are subject to dev availability and/or interest**_

**Game**
- [X] Scarlet/Violet
- [ ] Sword/Shield
- [ ] Brilliant Diamond/Shining Pearl
- [ ] Legend Arceus
- [ ] Nintendo Switch Features

**Type**
- [ ] New Program
- [X] Improvement to **_(Tera Self Farmer)_**

**Description**
The Tera Self Farmer Program needs an auto-restart feature added in after about 10 cycles or so.  There's such a significant reduction in framerate the longer the program runs...it eventually crashes after about 10-20 cycles.  Closing the game and restarting seems to fully refresh the game.

**Comment by Mysticial** [comment]
This already exists.
![image](https://github.com/PokemonAutomation/ComputerControl/assets/4991305/484d8719-06e9-4cd5-ac37-77aa384ecba2)

**Comment by PhoenixRising26** [comment]
My bad.  I must be running on an older version.  Thank you!

**Comment by PhoenixRising26** [comment]
Just downloaded the latest.  It's there.  Again, my bad!  Thanks again.
