### ISSUE TITLE
DLC2 Indigo Disk Program Recheck

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/ComputerControl#165]
Re-test list for DLC2:
- [x] Mass Purchase
- [x] Clothing Buyer
- [x] Autonomous Ball Thrower
- [x] Size Checker
- [x] Self Box Trade
- [x] Sandwich Maker
- [x] Mass Release
- [ ] Mass Attach Items
- [ ] LP Farmer
- [x] Gimmighoul Roaming Farmer
- [x] Gimmighoul Chest Farmer
- [ ] Auction Farmer
- [x] ESP Training
- [ ] Tournament Farmer
- [ ] Egg Fetcher
- [x] Egg Hatcher
- [x] Egg Autonomous
- [x] Auto-Host
- [ ] Tera Roller
- [x] Tera Self Farmer
- [ ] Tera Multi-Farmer
- [x] Fast Code Entry (FCE)
- [x] Clipboard Fast Code Entry (C-FCE)
- [x] Video Fast Code Entry (V-FCE)
- [x] Stats Reset
- [x] Stats Reset Bloodmoon Ursaluna
- [x] Shiny Hunt - Area Zero Platform

Intuition tells me that the most likely ones to break are:
- Self Box Trade (if box timings change)
- Sandwich Maker (new ingredients)
- Mass Release (if box timings change)
- Mass Attach Items (if box timings change)
- Tournament Farmer (new tourny mechanics like in SwSh?)
- Egg Hatcher (if box timings change)
- Egg Autonomous (if box timings change)
- Auto-Host (new Pokemon and sprites)
- Tera Roller (new Pokemon and sprites)
- Tera Self Farmer (new Pokemon and sprites)
- Tera Multi-Farmer (too many menu timings involved)
- Shiny Hunt - Area Zero Platform (if the platform changes due to DLC)

**Comment by kichithewolf** [comment]
Tested the following on v0.47.7 or latest commit, all tested after updating the game but before starting DLC2:
Stats Reset Bloodmoon Ursaluna
Stats Reset (tested on Gimmighoul, will update for DLC targets when I get to them)
Gimmi Roaming
Gimmi Chest
Sandwich Maker (will break if there are new ingredients but didn't see anything in the datamines)
Clothing Buyer
ESP Training
Mass Release (tried on a box with empty spaces, some shinies, and some non-shinies)
LP Farmer (tried in Paldea, don't know if new raids in Blueberry will affect this)

**Comment by Mysticial** [comment]
Tera Self-Farmer is broken because there's a new color for summary screens.

- Orange (Paldea - Scarlet)
- Purple (Paldea - Violet)
- Green (Kitakami)
- Dark Blue (Terariun)

Hopefully fixed in: https://github.com/PokemonAutomation/Arduino-Source/commit/9f46cbf70df96504b234fb325aaad20d0596cad8

Not confident of the fix since the shade of blue is dark enough that color ratios are unstable.

**Comment by mistergij** [comment]
If it helps, I ran Egg Autonomous for over 5 hours without issue after the update.

**Comment by Mysticial** [comment]
Multiple people are reporting that Tournament Farmer is losing a lot now with the new DLC2 update. Sylveon can no longer reliably solo the entire tourney by spamming one move.

**Comment by Mysticial** [comment]
Platform bot is broken once you've unlocked flying.

**Comment by Mysticial** [comment]
This adds a checkbox to select the flying mode (glide only, flying). This should fix the platform bot: https://github.com/PokemonAutomation/Arduino-Source/commit/c5d56542a9792379546e3405cc1a3a41bce6cead
