### ISSUE TITLE
[REQ] - Flying Time Trial Farming For BP

### ISSUE THREAD

**Issue by Qas89** [PokemonAutomation/ComputerControl#167]
**Important**
- Add your title after **[REQ] - **
- **Replace** the space inside the **[ ]** with a **x** to mark one of the options
- Replace the text inside "()" with what is required
- _**Bear in mind requests are subject to dev availability and/or interest**_

**Game**
- [x] Scarlet/Violet
- [ ] Sword/Shield
- [ ] Brilliant Diamond/Shining Pearl
- [ ] Legend Arceus
- [ ] Nintendo Switch Features

**Type**
- [x] New Program
- [ ] Improvement to **_(Program Name)_**

**Description**
_(Farming BP in the Flying Time Trial. I think using this method can produce a passive income of BP since the easy or normal run would take less than 5 min to complete and yield about 120BP/hr - 240BP/hr. From my early experiment on the easy run, using the Turbo Macro Program, you are able to skip some rings to go to the end faster. The problem that i have encontered is the unstable frame rate mess up my movement setting me up off course and failing the trial.)_

**Additional context**
_(Start from the NPC, choose the difficulty level. Image recognition for when the trial start and finish. I am not sure if we need to check if we are succesuflly passing throught the rings. I added the json file for the macro starting in front of the NPC **!!! IS NOT RELIABLE !!!**)._
[macro1.json](https://github.com/PokemonAutomation/ComputerControl/files/13761531/macro1.json)

**Comment by NympheaR** [comment]
Hi thank you for the suggestion, this has already been worked on and are under testing since last week. You are welcomed to check/share any development ideas in our public arduino channels on discord as well.

**Comment by Qas89** [comment]
Thanks. I looked at the discord channels now that you mentioned, probably i should have looked earlier. I just wanna say that you guys ara doing a great job. Thank you again.
