### ISSUE TITLE
[REQ] - SV  Item Printer Automation

### ISSUE THREAD

**Issue by jon-dunn** [PokemonAutomation/ComputerControl#169]
**Game**
- [ ] Sword/Shield
- [ ] Brilliant Diamond/Shining Pearl
- [ ] Legend Arceus
- [x] Scarlet/Violet
- [ ] Nintendo Switch Features

**Type**
- [x] New Program
- [ ] Improvement to **_(Program Name)_**

**Description**
A program to automate the item printer in S/V Blueberry Academy. 

**Additional context**
Use auto select for materials, print the items, handle ball lotto and double items. Set limit for number of prints to do.

**Comment by Mysticial** [comment]
This has been added to the program.
