### ISSUE TITLE
PokemonSwSh: Egg Fetcher Multiple is not consistent

### ISSUE THREAD

**Issue by Trentflix** [PokemonAutomation/ComputerControl#32]
I'm using the English-language game and haven't had any issues with any other SwSh programs yet. I've followed the instructions and gotten it to work once, but the majority of the time the program will end up taking the slot 1 pokemon, leaving the slot 2 pokemon by itself while cycling trying to grab eggs. The one time it did work, it quickly got messed up again (but I wasn't watching it closely). Seems some of the timings might be a little off?

What usually happens: The program will grab pokemon in slot 2 correctly, replace it with the correct pokemon in the first position in the box, quits to the overworld, but then talks to the lady again and grabs the pokemon in slot 1 before starting to cycle (which I believe at this point the program is supposed to be teleporting again to route 5 - not sure though).

I have text fast, send to boxes auto, casual mode off, etc.

I love the idea of this program, it will help speed up my IV breeding over the 'Egg Fetcher 2'. (and looking forward to trying the BDSP autonomous egg hatching!)

**Comment by Mysticial** [comment]
Is this still an issue. Sounds like it was resolved in the server?

**Comment by Trentflix** [comment]
Apologies, I opened this up after posting in Discord. It is still an issue. It did work once (and then I edited my discord comments), but then later the program got off again (I assume the next time it tried to swap parents). Subsequent retries didn't work either.

**Comment by Mysticial** [comment]
You will need to provide a full video with logging showing the issue. Then hopefully @pifopi will take a look at it.

**Comment by Trentflix** [comment]
Here is a Video: https://www.youtube.com/watch?v=AGbSunBAlcc
And Log File: https://pastebin.com/K0nN7WaK

**Comment by Trentflix** [comment]
Just realized you may have meant, record a video with the log visible in the video, re-recorded here: https://youtu.be/uTf1GK_Pl8k

**Comment by pifopi** [comment]
Thanks ! I'll look at it tonight (sorry I thought the issue was fixed after you tried again)

**Comment by pifopi** [comment]
@Trentflix I may have a "fix" could you rename "BABYMAKER" with "A" or something shorter ? I think it is because the text is slighty longer in english, causing one "a" press to happen before the text is fully displayed (so it doesn't go to the next)
https://youtu.be/fiQ_gw3hLA0?t=24
vs
https://youtu.be/uTf1GK_Pl8k?t=26

In the meantime, I'll increase slighty the delay before pressing that button and it should be available for next release !

**Comment by Trentflix** [comment]
That makes sense, thank you!

**Comment by pifopi** [comment]
https://github.com/PokemonAutomation/Arduino-Source/pull/82
