### ISSUE TITLE
[REQ] - Add option to BDSP money farming programs to choose just + (not with a direction) as your registered shortcut for the VS Seeker

### ISSUE THREAD

**Issue by karasuhebi** [PokemonAutomation/ComputerControl#71]
**Game**
- [ ] Sword/Shield
- [X] Brilliant Diamond/Shining Pearl
- [ ] Legend Arceus
- [ ] Nintendo Switch Features

**Type**
- [ ] New Program
- [X] Improvement to **Money Farmer**

**Description**
Can the BDSP money farming programs give you the option of choosing the registered shortcut for the VS Seeker just be + instead of one of + plus one of the directions? I purposely don't have any other items registered to save time.

**Comment by Mysticial** [comment]
Was done a while back, but forgot to update here.

**Comment by karasuhebi** [comment]
Thank you!
