### ISSUE TITLE
Max Lair - Standard not taking shiny pokemon - reporting errors

### ISSUE THREAD

**Issue by cjmasini** [PokemonAutomation/ComputerControl#85]
I set up the 'Max Lair -Standard' program to run over the weekend. Below is a picture of my results. Though a total of 17 shiny pokemon were encountered, none were actually taken by the program. It used all of my pokeballs, so I can confirm that it did in fact run the entire time.  I also see 18 errors, which I suspect occurred whenever the program tried to select a pokemon, but I have never been around to witness one of these errors. Is there anywhere the program logs data so I can see what the error is? Or any other troubleshooting ideas?
![image](https://user-images.githubusercontent.com/35500315/193593954-011166b6-2870-42c9-9f67-5eed18c1126b.png)

**Comment by Mysticial** [comment]
Did you forget to turn off nicknaming?

**Comment by cjmasini** [comment]
This was the issue. Thank you
