### ISSUE TITLE
Add sprites and silhouettes for SV:

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/ComputerControl#96]
SV versions of these:

https://github.com/PokemonAutomation/Packages/blob/master/SerialPrograms/Resources/PokemonSwSh/PokemonSprites.json
https://github.com/PokemonAutomation/Packages/blob/master/SerialPrograms/Resources/PokemonSwSh/PokemonSprites.png
https://github.com/PokemonAutomation/Packages/blob/master/SerialPrograms/Resources/PokemonSwSh/PokemonSilhouettes.png

**Comment by pifopi** [comment]
Already done
