### ISSUE TITLE
Shiny Tera Raid finder.

### ISSUE THREAD

**Issue by Mysticial** [PokemonAutomation/ComputerControl#99]
Assuming Tera raids can be re-hosted much like Sw/Sh, we'll need a way to find a shiny one.

While there's no easy way to detect a shiny raid, we can still battle and catch it, then check the summary. Will be very slow, but better than nothing.

**Comment by josegron** [comment]
Why not insert the shiny entrance of each possible entry, cause they are already in the code of the game of footage from streams, thus one can make it compare and save time from there and not battle and catch summary.

**Comment by Mysticial** [comment]
I doubt they're "coded" - most likely rendered since there's 400+ Pokemon x 18 Tera types.

Image/video matching isn't that simple. Even if you were going by exact match, you still have to account for brightness and color distortions across different capture cards.
